### ISSUE TITLE
bundle.js not found

### ISSUE THREAD

**Issue by joshuaterrill** [substack/shipboard#1]
After running ``` npm install -g shipboard ``` and ``` shipboard -p 9000 ``` I get taken to a blank page which logs out a 404 on ``` bundle.js ```

**Comment by kchanzen** [comment]
same issue.

**Comment by substack** [comment]
Sorry about that. All better in 1.0.2:

```
$ curl -s https://registry.npmjs.org/shipboard/-/shipboard-1.0.2.tgz | tar tz | grep bundle.js
package/public/bundle.js.gz
```
